@startuml L2PS DL FIFO Flowchart
start
:Event;
partition ProcessEvent {
    :eventToBeDelayed = false;
    if (eventToPassthrough?) then (true)
        :Dispatch event by FSM and handle Event;
        if (eventToBeDelayed?) then (true)
            (A)
            :Push event to back of FifoQueue (queuesDelayedEvents) \naccording to priority;
        endif
    else (false)
        (A)
    endif
}

partition ProcessDelayedEvents {
    while (queuesDelayedEvents.isEmpty()? and eventFlushForbidden?) is (false)
        :Pop delayed event from FifoQueue according to priority;
        if (isEnoughTimeInSlot?) then (no)
            break
        else (yes)
            :eventToBeDelayed = false;
            :Dispatch delayed event by FSM and handle Event;
            if (eventToBeDelayed?) then (true)
                :Push event to front of FifoQueue according to priority;
                break
            else (false)
            endif        
        endif
    endwhile
}
stop
@enduml